# Setup
title:               Ruben Flam-Shepherd
tagline:             'I should write more'
description:         'This is my personal blog. I write about sports analytics and data engineering'
url:                 https://rubenflamshepherd.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ruben Flam-Shepherd
  url:               https://twitter.com/rubenflamshepherd

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-KQP3XJ2T2Y
